"""
정책 DB / 대출상품 카탈로그 시드.

⚠️ 주의: 아래 자격요건 수치는 공개된 청년정책을 참고한 **데모용 근사값**이다.
   실제 공고 기준과 다를 수 있으므로, 제출본/발표 자료에 수치를 인용할 때는 반드시 원문 공고를 다시 확인할 것.
   (README에도 명시한 대로 이 프로젝트는 합성·시뮬레이션 데이터 기반이다)

trigger_events 가 A파트 매칭의 핵심이다 — "어떤 생애주기 이벤트가 확정/예측되면
이 정책의 자격을 다시 따져봐야 하는가"를 정책마다 미리 붙여 둔 역인덱스.
"""

from sqlalchemy.orm import Session

from backend.db.models import LoanProduct, Policy

LOAN_PRODUCTS = [
    dict(
        product_id="KB-JEONSE-01",
        product_name="KB 청년전용 전세자금대출",
        product_type="전월세자금",
        rate_type="변동",
        min_rate=3.10,
        max_rate=4.50,
        max_amount=200_000_000,
        target_desc="만 19~34세 무주택 청년 세대주",
        min_age=19,
        max_age=34,
        max_annual_income=70_000_000,
        allowed_employment=None,
        allowed_housing=["전세", "월세", "부모동거"],
        allowed_marital=None,
        region_code=None,
        trigger_events=["취업", "이직", "독립(전세)", "결혼"],
    ),
    dict(
        product_id="KB-MONTHLY-01",
        product_name="KB 청년 보증부월세대출",
        product_type="전월세자금",
        rate_type="변동",
        min_rate=2.60,
        max_rate=3.80,
        max_amount=50_000_000,
        target_desc="월세 거주 청년, 보증금+월세 동시 지원",
        min_age=19,
        max_age=34,
        max_annual_income=50_000_000,
        allowed_employment=None,
        # 실제 임대차계약이 있어야 대출 실행이 되는 상품이라 '부모동거'는 제외
        # (같은 이름의 정책 POL-MONTHLY-BOJEUNG은 사전 신청 성격이라 부모동거도 허용 — 의도적 차이)
        allowed_housing=["월세"],
        allowed_marital=None,
        region_code=None,
        trigger_events=["취업", "독립(월세)"],
    ),
    dict(
        product_id="KB-CREDIT-01",
        product_name="KB 직장인 신용대출",
        product_type="신용대출",
        rate_type="변동",
        min_rate=4.20,
        max_rate=9.80,
        max_amount=100_000_000,
        target_desc="재직 6개월 이상 급여소득자",
        min_age=None,
        max_age=None,
        max_annual_income=None,
        allowed_employment=["정규직", "계약직"],
        allowed_housing=None,
        allowed_marital=None,
        region_code=None,
        trigger_events=["취업", "이직"],
    ),
    dict(
        product_id="KB-CREDIT-02",
        product_name="KB 프리랜서 소득증빙 신용대출",
        product_type="신용대출",
        rate_type="변동",
        min_rate=5.40,
        max_rate=12.00,
        max_amount=30_000_000,
        target_desc="프리랜서·플랫폼노동 종사자 (변동소득 인정)",
        min_age=None,
        max_age=None,
        max_annual_income=None,
        allowed_employment=["프리랜서", "플랫폼노동", "자영업"],
        allowed_housing=None,
        allowed_marital=None,
        region_code=None,
        trigger_events=["취업", "창업", "퇴직"],
    ),
    dict(
        product_id="KB-STUDENT-01",
        product_name="KB 학자금 대출",
        product_type="학자금",
        rate_type="주기형",   # 학기마다 금리가 재고시되는 학자금대출 특성 반영
        min_rate=1.70,
        max_rate=2.90,
        max_amount=20_000_000,
        target_desc="재학생·졸업 후 2년 이내",
        min_age=None,
        max_age=30,
        max_annual_income=None,
        allowed_employment=["학생", "무직"],
        allowed_housing=None,
        allowed_marital=None,
        region_code=None,
        trigger_events=["대학생"],
    ),
    dict(
        product_id="KB-BIZ-01",
        product_name="KB 청년 창업 사업자대출",
        product_type="사업자",
        rate_type="혼합형",
        min_rate=3.90,
        max_rate=7.50,
        max_amount=50_000_000,
        target_desc="사업자등록 1년 이내 청년 창업자",
        min_age=19,
        max_age=39,
        max_annual_income=None,
        allowed_employment=["자영업", "무직"],
        allowed_housing=None,
        allowed_marital=None,
        region_code=None,
        trigger_events=["창업"],
    ),
]


POLICIES = [
    dict(
        policy_id="POL-JEONSE-BTM",
        policy_name="청년전용 버팀목전세자금대출",
        provider="주택도시기금",
        category="주거",
        benefit_summary="만 19~34세 무주택 청년 대상 전세보증금 최대 2억원, 연 2.0~3.1% 저리 대출",
        apply_url="https://nhuf.molit.go.kr",
        min_age=19,
        max_age=34,
        max_annual_income=50_000_000,
        allowed_employment=None,
        allowed_housing=["전세", "월세", "부모동거"],
        allowed_marital=None,
        region_code=None,
        trigger_events=["취업", "이직", "독립(전세)", "결혼"],
        priority=1,
        benefit_rate_pct=2.00,
    ),
    dict(
        policy_id="POL-MONTHLY-BOJEUNG",
        policy_name="청년전용 보증부월세대출",
        provider="주택도시기금",
        category="주거",
        benefit_summary="보증금 최대 4,500만원(연 1.3%) + 월세 최대 월 40만원(연 1.0%) 대출",
        apply_url="https://nhuf.molit.go.kr",
        min_age=19,
        max_age=34,
        max_annual_income=20_000_000,
        allowed_employment=None,
        allowed_housing=["월세", "부모동거"],
        allowed_marital=["미혼"],
        region_code=None,
        trigger_events=["취업", "독립(월세)"],
        priority=1,
        benefit_rate_pct=1.00,
    ),
    dict(
        policy_id="POL-MONTHLY-GOVT",
        policy_name="청년월세 한시 특별지원",
        provider="국토교통부",
        category="주거",
        benefit_summary="월세 최대 20만원 x 12개월 현금 지원 (보증금 5천만원·월세 70만원 이하)",
        apply_url="https://www.bokjiro.go.kr",
        min_age=19,
        max_age=34,
        max_annual_income=36_000_000,
        allowed_employment=None,
        allowed_housing=["월세"],
        allowed_marital=["미혼"],
        region_code=None,
        trigger_events=["독립(월세)", "취업", "퇴직"],
        priority=2,
        benefit_amount_krw=2_400_000,
        benefit_period_month=12,
    ),
    dict(
        policy_id="POL-SEOUL-MONTHLY",
        policy_name="서울시 청년월세지원",
        provider="서울특별시",
        category="주거",
        benefit_summary="월 20만원 x 최대 10개월 월세 지원 (서울 거주 청년 1인가구)",
        apply_url="https://youth.seoul.go.kr",
        min_age=19,
        max_age=39,
        max_annual_income=36_000_000,
        allowed_employment=None,
        allowed_housing=["월세"],
        allowed_marital=["미혼"],
        region_code="11",
        trigger_events=["독립(월세)"],
        priority=2,
        benefit_amount_krw=2_000_000,
        benefit_period_month=10,
    ),
    dict(
        policy_id="POL-SME-JEONSE",
        policy_name="중소기업취업청년 전월세보증금대출",
        provider="주택도시기금",
        category="주거",
        benefit_summary="중소기업 재직 청년 대상 보증금 최대 1억원, 연 1.5% 초저리 대출",
        apply_url="https://nhuf.molit.go.kr",
        min_age=19,
        max_age=34,
        max_annual_income=35_000_000,
        allowed_employment=["정규직", "계약직"],
        allowed_housing=["전세", "월세", "부모동거"],
        allowed_marital=None,
        region_code=None,
        trigger_events=["취업", "이직", "독립(전세)", "독립(월세)"],
        priority=1,
        benefit_rate_pct=1.50,
    ),
    dict(
        policy_id="POL-JEONSE-BOJEUNG-FEE",
        policy_name="전세보증금 반환보증 보증료 지원",
        provider="국토교통부",
        category="주거",
        benefit_summary="청년 임차인의 전세보증금 반환보증 보증료 최대 30만원 환급",
        apply_url="https://www.khug.or.kr",
        min_age=19,
        max_age=39,
        max_annual_income=50_000_000,
        allowed_employment=None,
        allowed_housing=["전세"],
        allowed_marital=None,
        region_code=None,
        trigger_events=["독립(전세)"],
        priority=3,
        benefit_amount_krw=300_000,
    ),
    dict(
        policy_id="POL-NAEIL-CHAEUM",
        policy_name="청년내일채움공제",
        provider="고용노동부",
        category="고용",
        benefit_summary="중소기업 정규직 취업 청년이 2년 근속 시 목돈 1,200만원 형성 지원",
        apply_url="https://www.work24.go.kr",
        min_age=15,
        max_age=34,
        max_annual_income=42_000_000,
        allowed_employment=["정규직"],
        allowed_housing=None,
        allowed_marital=None,
        region_code=None,
        trigger_events=["취업", "이직"],
        priority=1,
        benefit_amount_krw=12_000_000,
        benefit_period_month=24,
    ),
    dict(
        policy_id="POL-DOYAK-ACCOUNT",
        policy_name="청년도약계좌",
        provider="금융위원회",
        category="금융",
        benefit_summary="5년 납입 시 정부기여금 + 비과세로 최대 5,000만원 목돈 마련",
        apply_url="https://www.kinfa.or.kr",
        min_age=19,
        max_age=34,
        max_annual_income=75_000_000,
        allowed_employment=None,
        allowed_housing=None,
        allowed_marital=None,
        region_code=None,
        trigger_events=["취업", "이직", "창업"],
        priority=2,
        benefit_amount_krw=50_000_000,
        benefit_period_month=60,
    ),
    dict(
        policy_id="POL-SUNSHINE-YOUTH",
        policy_name="햇살론유스",
        provider="서민금융진흥원",
        category="금융",
        benefit_summary="저소득·저신용 청년 대상 최대 1,200만원 생활자금 저리 대출 (연 3.6%)",
        apply_url="https://www.kinfa.or.kr",
        min_age=19,
        max_age=34,
        max_annual_income=35_000_000,
        allowed_employment=["프리랜서", "플랫폼노동", "계약직", "무직", "학생"],
        allowed_housing=None,
        allowed_marital=None,
        region_code=None,
        trigger_events=["퇴직", "졸업", "취업", "창업"],
        priority=2,
        benefit_rate_pct=3.60,
    ),
    dict(
        policy_id="POL-CHUIEOP-JIWON",
        policy_name="국민취업지원제도 (Ⅰ유형)",
        provider="고용노동부",
        category="고용",
        benefit_summary="구직촉진수당 월 50만원 x 6개월 + 취업지원 서비스",
        apply_url="https://www.work24.go.kr",
        min_age=15,
        max_age=69,
        max_annual_income=30_000_000,
        allowed_employment=["무직", "프리랜서", "플랫폼노동"],
        allowed_housing=None,
        allowed_marital=None,
        region_code=None,
        trigger_events=["퇴직", "졸업"],
        priority=1,
        benefit_amount_krw=3_000_000,
        benefit_period_month=6,
    ),
    dict(
        policy_id="POL-SEOUL-SUDANG",
        policy_name="서울시 청년수당",
        provider="서울특별시",
        category="고용",
        benefit_summary="미취업 청년에게 월 50만원 x 최대 6개월 활동지원금 지급",
        apply_url="https://youth.seoul.go.kr",
        min_age=19,
        max_age=34,
        max_annual_income=30_000_000,
        allowed_employment=["무직"],
        allowed_housing=None,
        allowed_marital=None,
        region_code="11",
        trigger_events=["퇴직", "졸업"],
        priority=2,
        benefit_amount_krw=3_000_000,
        benefit_period_month=6,
    ),
    dict(
        policy_id="POL-STARTUP-SCHOOL",
        policy_name="청년창업사관학교",
        provider="중소벤처기업부",
        category="창업",
        benefit_summary="창업 3년 이내 청년에게 사업화 자금 최대 1억원 + 보육 공간 지원",
        apply_url="https://start.kosmes.or.kr",
        min_age=19,
        max_age=39,
        max_annual_income=None,
        allowed_employment=["자영업", "무직"],
        allowed_housing=None,
        allowed_marital=None,
        region_code=None,
        trigger_events=["창업"],
        priority=1,
    ),
    dict(
        policy_id="POL-DURUNURI",
        policy_name="두루누리 사회보험료 지원",
        provider="근로복지공단",
        category="고용",
        benefit_summary="소규모 사업장 근로자·사업주의 고용보험·국민연금 보험료 최대 80% 지원",
        apply_url="https://www.insurancesupport.or.kr",
        min_age=None,
        max_age=None,
        max_annual_income=32_000_000,
        allowed_employment=["정규직", "계약직", "자영업"],
        allowed_housing=None,
        allowed_marital=None,
        region_code=None,
        trigger_events=["취업", "창업", "이직"],
        priority=4,
    ),
    dict(
        policy_id="POL-NEWLYWED-JEONSE",
        policy_name="신혼부부 전용 전세자금대출",
        provider="주택도시기금",
        category="결혼출산",
        benefit_summary="혼인 7년 이내 부부 대상 전세보증금 최대 3억원, 연 1.5~2.9% 대출",
        apply_url="https://nhuf.molit.go.kr",
        min_age=19,
        max_age=45,
        max_annual_income=75_000_000,
        allowed_employment=None,
        allowed_housing=["전세", "월세", "부모동거"],
        allowed_marital=["기혼"],
        region_code=None,
        trigger_events=["결혼", "독립(전세)"],
        priority=1,
        benefit_rate_pct=1.50,
    ),
    dict(
        policy_id="POL-NEWBORN-DIDIMDOL",
        policy_name="신생아 특례 디딤돌대출",
        provider="주택도시기금",
        category="결혼출산",
        benefit_summary="출산 2년 이내 가구 대상 주택구입자금 최대 5억원, 연 1.6~3.3% 대출",
        apply_url="https://nhuf.molit.go.kr",
        min_age=19,
        max_age=49,
        max_annual_income=130_000_000,
        allowed_employment=None,
        allowed_housing=None,
        allowed_marital=["기혼"],
        region_code=None,
        trigger_events=["출산", "내집마련"],
        priority=1,
        benefit_rate_pct=1.60,
    ),
]


def seed_catalog(db: Session) -> dict:
    """대출상품 + 정책 DB 적재 (idempotent — 이미 있으면 갱신)."""
    for row in LOAN_PRODUCTS:
        db.merge(LoanProduct(**row))
    for row in POLICIES:
        db.merge(Policy(**row))
    db.flush()
    return {"loan_products": len(LOAN_PRODUCTS), "policies": len(POLICIES)}
